/gripper_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    # TODO use_sim_time as argument
    use_sim_time: True  # comment when working with the robot
    joints:
      - gripper_right_finger_joint
      - gripper_left_finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 5.0
      gripper_right_finger_joint:
        goal: 0.02
      gripper_left_finger_joint:
        goal: 0.02
